name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch: 

# This explicitly grants the automated bot write permissions inside the code file
permissions:
  contents: write

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      # Updated from v3 to v4 to fix the Node.js deprecation warning message
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make an empty keep-awake commit
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Keeping Streamlit App Awake (Timer Reset)"
          git push
